version: '3'
services:
  app:
    build: 
      context: ./dockerfiles
      dockerfile: js.dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./frontend:/var/www/html
    labels:
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
    depends_on:
      - traefik

  api:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./backend:/var/www/html
    labels:
      - "traefik.http.routers.api.rule=(Host(`api.app.localhost`))"
    depends_on:
      - traefik
  
  traefik:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock