version: '3'
services:
  app:
    build: 
      context: ./dockerfiles
      dockerfile: js.dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./frontend:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`app.localhost`)
      - traefik.http.services.app.loadbalancer.server.port=8082

  api:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.app.localhost`)
      - traefik.http.services.api.loadbalancer.server.port=8081
  
  traefik:
    image: traefik:v2.10
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock